#!/usr/bin/env node
// Generates the bundled Tabler icon set:
//   app/src/main/res/drawable/tab_*.xml   (Android vector drawables)
//   app/src/main/assets/tabler_tags.json  (icon name -> search tags)
//   app/src/main/java/ca/urbanlight/imagescale/icons/IconIndex.kt
//
// Usage:
//   node tools/generate-icons.mjs            # downloads @tabler/icons from npm
//   node tools/generate-icons.mjs --pkg DIR  # uses an extracted package dir
//
// Output is committed to the repo; builds never run this script.

import { execSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync, readdirSync, rmSync, copyFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DRAWABLE_DIR = join(ROOT, 'app/src/main/res/drawable');
const ASSETS_DIR = join(ROOT, 'app/src/main/assets');
const INDEX_KT = join(ROOT, 'app/src/main/java/ca/urbanlight/imagescale/icons/IconIndex.kt');
const LICENSE_OUT = join(ROOT, 'tools/TABLER_ICONS_LICENSE');

// Curated categories (~1000 icons). Brand logos deliberately excluded.
const CATEGORIES = new Set(['Photography', 'Media', 'Document', 'Arrows', 'Shapes', 'Communication', 'Math']);

async function resolvePackageDir() {
  const argIdx = process.argv.indexOf('--pkg');
  if (argIdx !== -1) return process.argv[argIdx + 1];
  const meta = await (await fetch('https://registry.npmjs.org/@tabler/icons/latest')).json();
  const work = join(tmpdir(), 'tabler-icons-pkg');
  rmSync(work, { recursive: true, force: true });
  mkdirSync(work, { recursive: true });
  const tgz = join(work, 'pkg.tgz');
  const buf = Buffer.from(await (await fetch(meta.dist.tarball)).arrayBuffer());
  writeFileSync(tgz, buf);
  execSync(`tar xzf ${tgz} -C ${work}`);
  console.log(`Fetched @tabler/icons ${meta.version}`);
  return join(work, 'package');
}

// Tabler outline SVGs are machine-generated: 24x24, stroke paths only.
function svgToVectorDrawable(svg, name) {
  const paths = [];
  const pathRe = /<path\b([^>]*)\/>/g;
  let m;
  while ((m = pathRe.exec(svg)) !== null) {
    const attrs = {};
    const attrRe = /([\w-]+)="([^"]*)"/g;
    let a;
    while ((a = attrRe.exec(m[1])) !== null) attrs[a[1]] = a[2];
    if (!attrs.d) continue;
    if (attrs.stroke === 'none' && attrs.fill === 'none') continue; // bounding-box rect
    paths.push(attrs);
  }
  if (paths.length === 0) throw new Error(`no paths in ${name}`);
  const body = paths
    .map((p) => {
      const filled = p.fill && p.fill !== 'none';
      const paint = filled
        ? `        android:fillColor="#FF000000"`
        : `        android:fillColor="#00000000"
        android:strokeColor="#FF000000"
        android:strokeWidth="2"
        android:strokeLineCap="round"
        android:strokeLineJoin="round"`;
      return `    <path
        android:pathData="${p.d}"
${paint} />`;
    })
    .join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24"
    android:tint="?android:attr/colorControlNormal">
${body}
</vector>
`;
}

const resName = (name) => 'tab_' + name.replace(/-/g, '_');

const pkg = await resolvePackageDir();
const icons = JSON.parse(readFileSync(join(pkg, 'icons.json'), 'utf8'));
const selected = Object.values(icons)
  .filter((i) => CATEGORIES.has(i.category) && i.styles?.outline)
  .sort((a, b) => a.name.localeCompare(b.name));

// Wipe previously generated drawables so removals don't linger.
mkdirSync(DRAWABLE_DIR, { recursive: true });
for (const f of readdirSync(DRAWABLE_DIR)) if (f.startsWith('tab_')) rmSync(join(DRAWABLE_DIR, f));
mkdirSync(ASSETS_DIR, { recursive: true });
mkdirSync(dirname(INDEX_KT), { recursive: true });

const tagsOut = [];
const indexEntries = [];
for (const icon of selected) {
  const svg = readFileSync(join(pkg, 'icons/outline', `${icon.name}.svg`), 'utf8');
  const res = resName(icon.name);
  writeFileSync(join(DRAWABLE_DIR, `${res}.xml`), svgToVectorDrawable(svg, icon.name));
  tagsOut.push({ name: icon.name, res, category: icon.category, tags: icon.tags ?? [] });
  indexEntries.push(`        "${icon.name}" to R.drawable.${res},`);
}

writeFileSync(join(ASSETS_DIR, 'tabler_tags.json'), JSON.stringify(tagsOut));
writeFileSync(
  INDEX_KT,
  `// GENERATED by tools/generate-icons.mjs — do not edit by hand.
package ca.urbanlight.imagescale.icons

import ca.urbanlight.imagescale.R

object IconIndex {
    val byName: Map<String, Int> = mapOf(
${indexEntries.join('\n')}
    )

    const val FALLBACK = "photo"

    fun resFor(name: String): Int = byName[name] ?: byName.getValue(FALLBACK)
}
`,
);
copyFileSync(join(pkg, 'LICENSE'), LICENSE_OUT);
console.log(`Generated ${selected.length} icons.`);
